### PR TITLE
all FxBx(s/4)

### PR DESCRIPTION
**Pull request by zhizhangxian**
all cell's channel are all FxBx(s/4), maybe

### CODE REVIEW

**Comment by HankKung** [comment]
Seems great! Have you tested it to check if it works fine?

**Comment by zhizhangxian** [comment]
> Seems great! Have you tested it to check if it works fine?

I test it for 19 epochs now, and the miou is shown in figure. It looks like the miou and pixel accuracy is not stable, do you have some advice?
image

**Comment by zhizhangxian** [comment]
by the way, when I retrain the autodeeplab in cityscapes just like the result searched by paper, Result is also not stable.....

**Comment by HankKung** [comment]
Did you set the image size and crop size as same as the numbers on paper both when search and retrain?

**Comment by zhizhangxian** [comment]
> Did you set the image size and crop size as same as the numbers on paper both when search and retrain?

I set 384 and 320.... Now I don't know how to apply size with 321

**Comment by HankKung** [comment]
does new_model.py file also adopt new filter config and set F as 20?
I have this problem that can not set crop size to an odd number as well...
I'll test it again with the properly resized image and your change.

**Comment by zhizhangxian** [comment]
> does new_model.py file also adopt new filter config and set F as 20?
> I have this problem that can not set crop size to an odd number as well...
> I'll test it again with the properly resized image and your change.

No, filter in new_model.py is still wrong, I haven't reproduce the params and flops in paper(695B and 44.42M), if you have some ideas, please tell me.
Also, i cann't reproduce the 1551.05B and 43.48M deeplab v3 too,  My version is 1478B and 45M

**Comment by NoamRosenberg** [comment]
@zhizhangxian @HankKung at this point our version could be more optimized than the authors. I’ve made a lot of efforts to share weights when possible, so let’s not worry about reproducing flops, let’s get the Same or better results with the same or less memory usage and the same or lesss speed given the same GPU.

**Pull request merged**
